#!/usr/bin/env python3
"""NOVA autonomous recursive self-improvement engine.

The engine asks a configured OpenAI-compatible AI proposer for one improvement
candidate, validates its patch, tests it in a detached Git worktree, and
produces machine-readable evidence. It never writes to main by itself.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


PROTECTED_PREFIXES = (
    '.github/',
    'development/nova-recursive-self-improvement/evaluator.py',
    'development/nova-recursive-self-improvement/rsi_engine.py',
    'development/nova-recursive-self-improvement/rsi_policy.json',
    'development/nova-recursive-self-improvement/candidate.schema.json',
    'development/nova-recursive-self-improvement/tests/',
)

FORBIDDEN_FRAGMENTS = (
    '.env', 'credentials', 'secret', 'private_key', 'id_rsa',
)

SECRET_PATTERNS = [
    re.compile(r'BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY', re.IGNORECASE),
    re.compile(r'(?:api[_-]?key|access[_-]?token|auth[_-]?token)\s*[:=]', re.IGNORECASE),
]

MAX_CONTEXT_CHARS = int(os.environ.get('RSI_MAX_CONTEXT_CHARS', '120000'))


def git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ['git', *args], cwd=root, text=True, stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT, check=True
    )
    return result.stdout.strip()


def extract_candidate_payload(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        payload = json.loads(text)
        if isinstance(payload, dict) and payload.get('patch'):
            return payload
    except json.JSONDecodeError:
        pass

    fenced = re.search(r'```(?:diff|patch)\s*(.*?)```', text, re.DOTALL | re.IGNORECASE)
    patch = fenced.group(1).strip() if fenced else ''
    if not patch:
        start = text.find('diff --git ')
        if start >= 0:
            patch = text[start:].strip()
    if not patch:
        raise ValueError('AI proposer did not return a JSON candidate or unified diff.')

    return {
        'candidate_id': f'ai-{int(time.time())}',
        'hypothesis': 'AI-generated repository improvement candidate.',
        'rationale': 'Generated by the configured NOVA RSI proposer.',
        'expected_improvement': '',
        'risks': '',
        'patch': patch,
    }


def changed_paths_from_patch(patch: str) -> list[str]:
    paths: set[str] = set()
    for line in patch.splitlines():
        if line.startswith('+++ b/'):
            paths.add(line[6:])
        elif line.startswith('--- a/') and line[6:] != '/dev/null':
            paths.add(line[6:])
        elif line.startswith('diff --git '):
            parts = line.split()
            if len(parts) >= 4:
                for item in parts[2:4]:
                    if item.startswith(('a/', 'b/')):
                        paths.add(item[2:])
    return sorted(paths)


def validate_patch_paths(paths: list[str]) -> list[str]:
    errors: list[str] = []
    for path in paths:
        normalized = path.replace('\\', '/').lstrip('./')
        if not normalized.startswith('development/'):
            errors.append(f'Outside allowed development scope: {path}')
        if any(fragment in normalized.lower() for fragment in FORBIDDEN_FRAGMENTS):
            errors.append(f'Forbidden sensitive path: {path}')
        if normalized.startswith(PROTECTED_PREFIXES):
            errors.append(f'Protected path: {path}')
    return sorted(set(errors))


def validate_patch_content(patch: str) -> list[str]:
    return [pattern.pattern for pattern in SECRET_PATTERNS if pattern.search(patch)]


def classify_decision(statuses: list[str]) -> str:
    if 'FAIL' in statuses:
        return 'FAIL'
    if 'BLOCKED' in statuses:
        return 'BLOCKED'
    return 'PASS'


def repository_context(root: Path) -> str:
    files = git(root, 'ls-files', 'development').splitlines()
    chunks: list[str] = []
    total = 0
    for relative in files:
        lower = relative.lower()
        if any(fragment in lower for fragment in FORBIDDEN_FRAGMENTS):
            continue
        path = root / relative
        if not path.is_file():
            continue
        try:
            data = path.read_text(encoding='utf-8')
        except (UnicodeDecodeError, OSError):
            continue
        remaining = MAX_CONTEXT_CHARS - total
        if remaining <= 0:
            break
        clipped = data[:remaining]
        chunks.append(f'\n===== {relative} =====\n{clipped}')
        total += len(clipped)
    return ''.join(chunks)


def proposer_prompt(root: Path, baseline: str) -> str:
    context = repository_context(root)
    return f'''You are the improvement proposer inside NOVA's recursive self-improvement system.

Repository: ACROWN-System/AstroCrown-Web
Baseline commit: {baseline}

Identify ONE concrete, testable improvement to the current development system.

Hard constraints:
- Work only within development/.
- Do not modify evaluator.py, rsi_engine.py, rsi_policy.json, candidate.schema.json, tests/, or .github/.
- Do not add credentials, secrets, private keys, or sensitive configuration.
- Preserve existing requirements, evidence, provenance, and uncertainty.
- Prefer the minimum necessary change.
- The candidate must have a measurable hypothesis that can be tested against the baseline.
- Do not claim success; propose a change for protected evaluation.
- Return JSON only with: candidate_id, hypothesis, rationale, expected_improvement, risks, patch.
- patch must be a valid unified Git patch.

Current repository development context:
{context}
'''


def call_proposer(prompt: str) -> dict[str, Any]:
    base_url = os.environ.get('RSI_AI_BASE_URL', '').strip()
    model = os.environ.get('RSI_AI_MODEL', '').strip()
    api_key = os.environ.get('RSI_AI_API_KEY', '').strip()
    if not base_url or not model or not api_key:
        raise RuntimeError('RSI_AI_BASE_URL, RSI_AI_MODEL, and RSI_AI_API_KEY must be configured.')

    payload = {
        'model': model,
        'messages': [
            {'role': 'system', 'content': 'You are a code-improvement proposer. Return only the requested JSON and never include secrets.'},
            {'role': 'user', 'content': prompt},
        ],
        'temperature': 0.1,
    }
    request = urllib.request.Request(
        base_url,
        data=json.dumps(payload).encode('utf-8'),
        headers={
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {api_key}',
            'User-Agent': 'NOVA-RSI/1.0',
        },
        method='POST',
    )
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            result = json.loads(response.read().decode('utf-8'))
    except urllib.error.HTTPError as exc:
        body = exc.read().decode('utf-8', errors='ignore')
        raise RuntimeError(f'RSI proposer HTTP {exc.code}: {body[:1000]}') from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f'RSI proposer connection failure: {exc}') from exc

    content = result['choices'][0]['message']['content']
    return extract_candidate_payload(content)


def apply_and_evaluate(root: Path, baseline: str, candidate: dict[str, Any], evidence_dir: Path) -> dict[str, Any]:
    patch = str(candidate['patch'])
    paths = changed_paths_from_patch(patch)
    path_errors = validate_patch_paths(paths)
    content_errors = validate_patch_content(patch)
    if path_errors or content_errors:
        return {
            'decision': 'FAIL',
            'stage': 'candidate-validation',
            'path_errors': path_errors,
            'content_errors': content_errors,
            'candidate': candidate,
        }

    worktree = Path(tempfile.mkdtemp(prefix='nova-rsi-'))
    worktree_root = worktree / 'repo'
    try:
        subprocess.run(
            ['git', 'worktree', 'add', '--detach', str(worktree_root), baseline],
            cwd=root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        patch_file = evidence_dir / 'candidate.patch'
        patch_file.write_text(patch + '\n', encoding='utf-8')
        subprocess.run(
            ['git', 'apply', '--check', str(patch_file)],
            cwd=worktree_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        subprocess.run(
            ['git', 'apply', '--index', str(patch_file)],
            cwd=worktree_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        subprocess.run(['git', 'config', 'user.name', 'NOVA RSI Candidate'], cwd=worktree_root, check=True)
        subprocess.run(['git', 'config', 'user.email', 'nova-rsi@localhost'], cwd=worktree_root, check=True)
        subprocess.run(
            ['git', 'commit', '-m', f"rsi(candidate): {candidate['candidate_id']}"],
            cwd=worktree_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        candidate_commit = git(worktree_root, 'rev-parse', 'HEAD')

        evaluator_path = worktree_root / 'development/nova-recursive-self-improvement/evaluator.py'
        policy_path = worktree_root / 'development/nova-recursive-self-improvement/rsi_policy.json'
        candidate_evidence = evidence_dir / 'evaluation.json'
        env = {
            'PATH': os.environ.get('PATH', ''),
            'HOME': str(Path.home()),
            'LANG': 'C.UTF-8',
            'LC_ALL': 'C.UTF-8',
            'PYTHONUNBUFFERED': '1',
            'RSI_BENCHMARK_COMMAND': os.environ.get('RSI_BENCHMARK_COMMAND', ''),
        }
        completed = subprocess.run(
            ['python', str(evaluator_path), '--baseline', baseline, '--policy', str(policy_path), '--output', str(candidate_evidence)],
            cwd=worktree_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            timeout=360, env=env, check=False
        )
        evaluation = json.loads(candidate_evidence.read_text(encoding='utf-8'))
        return {
            'decision': evaluation['decision'],
            'candidate_commit': candidate_commit,
            'candidate': candidate,
            'evaluator_exit_code': completed.returncode,
            'evaluator_output': completed.stdout[-16000:],
        }
    except subprocess.TimeoutExpired:
        return {'decision': 'FAIL', 'stage': 'candidate-execution', 'error': 'Protected evaluation timed out.', 'candidate': candidate}
    except subprocess.CalledProcessError as exc:
        return {'decision': 'FAIL', 'stage': 'candidate-execution', 'error': str(exc), 'candidate': candidate}
    finally:
        subprocess.run(['git', 'worktree', 'remove', '--force', str(worktree_root)], cwd=root, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)
        shutil.rmtree(worktree, ignore_errors=True)


def cycle(root: Path, evidence_dir: Path) -> int:
    evidence_dir.mkdir(parents=True, exist_ok=True)
    baseline = git(root, 'rev-parse', 'HEAD')
    started = time.monotonic()
    evidence: dict[str, Any] = {
        'schema_version': 1,
        'baseline_commit': baseline,
        'started_at': time.time(),
    }
    try:
        candidate = call_proposer(proposer_prompt(root, baseline))
        candidate['baseline_commit'] = baseline
        evidence['candidate'] = candidate
        evidence['result'] = apply_and_evaluate(root, baseline, candidate, evidence_dir)
    except Exception as exc:
        evidence['result'] = {'decision': 'BLOCKED', 'stage': 'proposal', 'error': str(exc)}

    evidence['duration_seconds'] = round(time.monotonic() - started, 3)
    evidence['decision'] = evidence['result']['decision']
    (evidence_dir / 'cycle.json').write_text(json.dumps(evidence, indent=2, sort_keys=True) + '\n', encoding='utf-8')
    print(json.dumps(evidence, indent=2, sort_keys=True))
    return 0 if evidence['decision'] == 'PASS' else 1


def main() -> int:
    parser = argparse.ArgumentParser(description='Run one NOVA autonomous RSI cycle.')
    parser.add_argument('command', choices=['cycle'])
    parser.add_argument('--repo', default='.')
    parser.add_argument('--evidence-dir', default='.rsi-evidence')
    args = parser.parse_args()
    return cycle(Path(args.repo).resolve(), Path(args.evidence_dir).resolve())


if __name__ == '__main__':
    raise SystemExit(main())
