#!/usr/bin/env python3
"""NOVA autonomous recursive self-improvement engine.

The engine asks a configured OpenAI-compatible AI proposer for one improvement
candidate, validates its patch, tests it in a detached Git worktree, and
produces machine-readable evidence. It never writes to main by itself.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Any

from provider_client import ProviderConfig, ProviderError, chat_completion


SECRET_PATTERNS = [
    re.compile(r'BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY', re.IGNORECASE),
    re.compile(
        r'(?:api[_-]?key|access[_-]?token|auth[_-]?token|password|client[_-]?secret)\s*[:=]',
        re.IGNORECASE,
    ),
    re.compile(r'(?:ghp_|github_pat_|sk-[A-Za-z0-9]{16,}|AKIA[0-9A-Z]{16})'),
    re.compile(r'Authorization\s*:\s*Bearer\s+[A-Za-z0-9._-]{12,}', re.IGNORECASE),
]

def load_policy(root: Path) -> dict[str, Any]:
    path = root / 'development/nova-recursive-self-improvement/rsi_policy.json'
    return json.loads(path.read_text(encoding='utf-8'))



def git(root: Path, *args: str) -> str:
    result = subprocess.run(
        ['git', *args], cwd=root, text=True, stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT, check=True
    )
    return result.stdout.strip()


def extract_candidate_payload(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        payload = json.loads(text)
        if isinstance(payload, dict) and payload.get('patch'):
            return payload
    except json.JSONDecodeError:
        pass

    fenced = re.search(r'```(?:diff|patch)\s*(.*?)```', text, re.DOTALL | re.IGNORECASE)
    patch = fenced.group(1).strip() if fenced else ''
    if not patch:
        start = text.find('diff --git ')
        if start >= 0:
            patch = text[start:].strip()
    if not patch:
        raise ValueError('AI proposer did not return a JSON candidate or unified diff.')

    return {
        'candidate_id': f'ai-{int(time.time())}',
        'hypothesis': 'AI-generated repository improvement candidate.',
        'rationale': 'Generated by the configured NOVA RSI proposer.',
        'expected_improvement': '',
        'risks': '',
        'patch': patch,
    }


def normalize_repo_path(path: str) -> str:
    candidate = path.replace('\\\\', '/')
    if candidate.startswith('/') or re.match(r'^[A-Za-z]:/', candidate):
        return ''
    parts = []
    for part in candidate.split('/'):
        if part in {'', '.'}:
            continue
        if part == '..':
            return ''
        parts.append(part)
    return '/'.join(parts)

def changed_paths_from_patch(patch: str) -> list[str]:
    raw_paths = set()
    for line in patch.splitlines():
        if line.startswith(('--- ', '+++ ')):
            raw = line[4:]
            if raw != '/dev/null':
                raw_paths.add(raw)
        elif line.startswith('diff --git '):
            parts = line.split()
            for item in parts[2:4]:
                if item.startswith(('a/', 'b/')):
                    raw_paths.add(item[2:])
    paths = []
    for raw in sorted(raw_paths):
        normalized = normalize_repo_path(raw)
        paths.append(normalized if normalized else f'UNSAFE_PATH:{raw}')
    return sorted(set(paths))

def validate_patch_paths(paths: list[str], policy: dict[str, Any]) -> list[str]:
    scope = policy["candidate_scope"]
    allowed_prefixes = tuple(scope["allowed_prefixes"])
    protected_paths = tuple(scope["protected_paths"])
    forbidden_fragments = tuple(scope["forbidden_path_fragments"])

    errors: list[str] = []
    for path in paths:
        normalized = normalize_repo_path(path)
        if not normalized:
            errors.append(f'Unsafe path: {path}')
            continue
        lowered = normalized.lower()
        if not any(normalized.startswith(prefix) for prefix in allowed_prefixes):
            errors.append(f'Outside allowed scope: {path}')
        if any(fragment.lower() in lowered for fragment in forbidden_fragments):
            errors.append(f'Forbidden sensitive path: {path}')
        if any(normalized.startswith(prefix) for prefix in protected_paths):
            errors.append(f'Protected path: {path}')
    return sorted(set(errors))


def validate_patch_content(patch: str) -> list[str]:
    findings = [pattern.pattern for pattern in SECRET_PATTERNS if pattern.search(patch)]
    if "GIT binary patch" in patch:
        findings.append("Binary patches are not permitted in RSI candidates.")
    if re.search(r"^rename (?:from|to) ", patch, re.MULTILINE | re.IGNORECASE):
        findings.append("Renames are not permitted in RSI candidates.")
    if re.search(r"^copy (?:from|to) ", patch, re.MULTILINE | re.IGNORECASE):
        findings.append("Copies are not permitted in RSI candidates.")
    return sorted(set(findings))



def validate_candidate_payload(
    candidate: dict[str, Any], baseline: str, policy: dict[str, Any]
) -> list[str]:
    errors: list[str] = []
    required = ("candidate_id", "baseline_commit", "hypothesis", "rationale", "patch")
    for field in required:
        if field not in candidate:
            errors.append(f"Missing candidate field: {field}")
    if errors:
        return errors
    if not isinstance(candidate["candidate_id"], str) or not re.fullmatch(
        r"[A-Za-z0-9._-]+", candidate["candidate_id"]
    ):
        errors.append("candidate_id contains unsupported characters.")
    if candidate["baseline_commit"] != baseline:
        errors.append("Candidate baseline_commit does not match the actual RSI baseline.")
    for field in ("hypothesis", "rationale", "expected_improvement", "risks", "patch"):
        if field in candidate and not isinstance(candidate[field], str):
            errors.append(f"Candidate field {field} must be a string.")
    patch = candidate.get("patch", "")
    limits = policy.get("candidate_limits", {})
    if isinstance(patch, str):
        if len(patch) > int(limits.get("max_patch_chars", 120000)):
            errors.append("Candidate patch exceeds the protected character limit.")
        if len(patch.splitlines()) > int(limits.get("max_patch_lines", 5000)):
            errors.append("Candidate patch exceeds the protected line limit.")
        if len(changed_paths_from_patch(patch)) > int(limits.get("max_patch_files", 20)):
            errors.append("Candidate patch changes more files than the protected file limit.")
    return sorted(set(errors))

def classify_decision(statuses: list[str]) -> str:
    if 'FAIL' in statuses:
        return 'FAIL'
    if 'BLOCKED' in statuses:
        return 'BLOCKED'
    return 'PASS'


def implementation_ready(policy: dict[str, Any]) -> bool:
    readiness = policy.get("implementation_readiness", {})
    return (
        readiness.get("status") == "READY"
        and readiness.get("require_explicit_ready") is True
        and readiness.get("promotion_blocked_until_ready") is True
    )


def repository_context(
    root: Path,
    max_context_chars: int,
    excluded_prefixes: tuple[str, ...],
    priority_prefixes: tuple[str, ...],
) -> tuple[str, int]:
    files = git(root, 'ls-files', 'development').splitlines()
    priority = [
        f for f in files
        if any(f.startswith(prefix) for prefix in priority_prefixes)
    ]
    remainder = [f for f in files if f not in priority]
    ordered = priority + remainder

    chunks: list[str] = []
    total = 0
    for relative in ordered:
        if any(relative.startswith(prefix) for prefix in excluded_prefixes):
            continue
        path = root / relative
        if not path.is_file():
            continue
        try:
            data = path.read_text(encoding='utf-8')
        except (UnicodeDecodeError, OSError):
            continue
        remaining = max_context_chars - total
        if remaining <= 0:
            break
        clipped = data[:remaining]
        chunks.append(f'\n===== {relative} =====\n{clipped}')
        total += len(clipped)
    return ''.join(chunks), total


def proposer_prompt(
    root: Path,
    baseline: str,
    max_context_chars: int,
    policy: dict[str, Any],
) -> tuple[str, int]:
    scope = policy["candidate_scope"]
    allowed_scope = ", ".join(scope["allowed_prefixes"])
    protected_paths = ", ".join(scope["protected_paths"])
    forbidden_paths = ", ".join(scope["forbidden_path_fragments"])
    context_policy = policy.get("context", {})
    context, context_chars = repository_context(
        root,
        max_context_chars,
        tuple(context_policy.get("excluded_prefixes", [])),
        tuple(context_policy.get("priority_prefixes", [])),
    )
    prompt = f'''You are the improvement proposer inside NOVA's recursive self-improvement system.

Repository: ACROWN-System/AstroCrown-Web
Baseline commit: {baseline}

Identify ONE concrete, testable improvement to the current development system.

Hard constraints from the protected RSI policy:
- Candidate changes must remain within: {allowed_scope}
- Protected paths that must not be modified: {protected_paths}
- Forbidden sensitive path fragments: {forbidden_paths}
- Preserve existing requirements, evidence, provenance, and uncertainty.
- Prefer the minimum necessary change.
- The candidate must have a measurable hypothesis that can be tested against the baseline.
- Do not claim success; propose a change for protected evaluation.
- Return JSON only with: candidate_id, hypothesis, rationale, expected_improvement, risks, patch.
- patch must be a valid unified Git patch.

Current repository development context:
{context}
'''
    return prompt, context_chars


def normalize_usage(raw_usage: Any) -> dict[str, int | None] | None:
    """Normalize only internally consistent, nonnegative integer token telemetry."""
    if not isinstance(raw_usage, dict):
        return None

    keys = ("prompt_tokens", "completion_tokens", "total_tokens")
    counts: dict[str, int | None] = {}
    for key in keys:
        value = raw_usage.get(key)
        if value is None:
            counts[key] = None
            continue
        # bool subclasses int in Python; fractional values must not be truncated.
        if isinstance(value, bool) or not isinstance(value, int) or value < 0:
            return None
        counts[key] = value

    prompt_tokens = counts["prompt_tokens"]
    completion_tokens = counts["completion_tokens"]
    total_tokens = counts["total_tokens"]

    if total_tokens is not None and total_tokens == 0:
        # An actual proposer request has a non-empty system/user prompt.
        return None
    if total_tokens is None and prompt_tokens is not None and completion_tokens is not None:
        total_tokens = prompt_tokens + completion_tokens
    elif (
        total_tokens is not None
        and prompt_tokens is not None
        and completion_tokens is not None
        and total_tokens != prompt_tokens + completion_tokens
    ):
        return None

    if prompt_tokens is None and completion_tokens is None and total_tokens is None:
        return None
    return {
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total_tokens,
    }

def call_proposer(prompt: str, max_output_tokens: int, policy: dict[str, Any]) -> tuple[dict[str, Any], dict[str, int | None] | None, str]:
    provider = policy["provider"]
    config = ProviderConfig.from_environment(
        base_url_env=provider["base_url_env"],
        model_env=provider["model_env"],
        api_key_env=provider["api_key_env"],
        default_base_url=provider.get("default_base_url"),
        timeout_seconds=int(policy["evaluation"].get("provider_timeout_seconds", 120)),
        allowed_hosts=provider.get("allowed_hosts"),
        max_response_bytes=int(provider.get("max_response_bytes", 262144)),
    )
    result, model = chat_completion(
        config,
        [
            {"role": "system", "content": "You are a code-improvement proposer. Return only the requested JSON and never include secrets."},
            {"role": "user", "content": prompt},
        ],
        max_output_tokens,
        temperature=0.1,
    )
    choices = result.get("choices")
    message = choices[0].get("message") if isinstance(choices, list) and choices and isinstance(choices[0], dict) else None
    content = message.get("content") if isinstance(message, dict) else None
    if not isinstance(content, str) or not content.strip():
        raise ProviderError("RSI provider returned no textual proposer content.")
    return extract_candidate_payload(content), normalize_usage(result.get("usage")), model

TRUSTED_CONTROL_FILENAMES = (
    "evaluator.py",
    "benchmark_dispatcher.py",
    "sandbox_runtime.py",
    "rsi_policy.json",
    "benchmark_profiles.json",
)


def materialize_trusted_control_plane(
    trusted_root: Path, control_dir: Path
) -> dict[str, Path]:
    """Copy protected evaluation controls outside the candidate worktree."""
    source_dir = (
        trusted_root / "development/nova-recursive-self-improvement"
    ).resolve()
    root = trusted_root.resolve()
    if source_dir != root and root not in source_dir.parents:
        raise RuntimeError("Trusted RSI control source escaped the repository root.")

    control_dir.mkdir(parents=True, exist_ok=False)
    copied: dict[str, Path] = {}
    for filename in TRUSTED_CONTROL_FILENAMES:
        source = source_dir / filename
        target = control_dir / filename
        if not source.is_file():
            raise FileNotFoundError(
                f"Trusted RSI control file is missing: {filename}"
            )
        shutil.copyfile(source, target)
        target.chmod(0o444)
        copied[filename] = target
    return copied


def apply_and_evaluate(
    root: Path,
    baseline: str,
    candidate: dict[str, Any],
    evidence_dir: Path,
    evaluation_timeout: int,
    policy: dict[str, Any],
) -> dict[str, Any]:
    patch = str(candidate['patch'])
    paths = changed_paths_from_patch(patch)
    path_errors = validate_patch_paths(paths, policy)
    content_errors = validate_patch_content(patch)
    payload_errors = validate_candidate_payload(candidate, baseline, policy)
    if path_errors or content_errors or payload_errors:
        return {
            'decision': 'FAIL',
            'stage': 'candidate-validation',
            'path_errors': path_errors,
            'content_errors': content_errors,
            'payload_errors': payload_errors,
            'candidate': candidate,
        }

    worktree = Path(tempfile.mkdtemp(prefix='nova-rsi-'))
    worktree_root = worktree / 'repo'
    try:
        subprocess.run(
            ['git', 'worktree', 'add', '--detach', str(worktree_root), baseline],
            cwd=root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        patch_file = evidence_dir / 'candidate.patch'
        patch_file.write_text(patch + '\n', encoding='utf-8')
        subprocess.run(
            ['git', 'apply', '--check', str(patch_file)],
            cwd=worktree_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        subprocess.run(
            ['git', 'apply', '--index', str(patch_file)],
            cwd=worktree_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        subprocess.run(['git', 'config', 'user.name', 'NOVA RSI Candidate'], cwd=worktree_root, check=True)
        subprocess.run(['git', 'config', 'user.email', 'nova-rsi@localhost'], cwd=worktree_root, check=True)
        subprocess.run(
            ['git', 'commit', '-m', f"rsi(candidate): {candidate['candidate_id']}"],
            cwd=worktree_root, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=True
        )
        candidate_commit = git(worktree_root, 'rev-parse', 'HEAD')

        control_files = materialize_trusted_control_plane(
            root,
            worktree / 'trusted-control',
        )
        evaluator_path = control_files['evaluator.py']
        policy_path = control_files['rsi_policy.json']
        profile_registry_path = control_files['benchmark_profiles.json']
        candidate_evidence = evidence_dir / 'evaluation.json'
        control_home = worktree / 'home'
        control_home.mkdir()
        env = {
            'PATH': os.environ.get('PATH', ''),
            'HOME': str(control_home),
            'XDG_CONFIG_HOME': str(control_home / '.config'),
            'XDG_CACHE_HOME': str(control_home / '.cache'),
            'LANG': 'C.UTF-8',
            'LC_ALL': 'C.UTF-8',
            'PYTHONUNBUFFERED': '1',
            'PYTHONNOUSERSITE': '1',
            'GIT_TERMINAL_PROMPT': '0',
            'GIT_CONFIG_NOSYSTEM': '1',
            'RSI_BENCHMARK_COMMAND': os.environ.get('RSI_BENCHMARK_COMMAND', ''),
        }
        completed = subprocess.run(
            [
                'python',
                str(evaluator_path),
                '--baseline',
                baseline,
                '--policy',
                str(policy_path),
                '--profile-registry',
                str(profile_registry_path),
                '--output',
                str(candidate_evidence),
            ],
            cwd=worktree_root,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=evaluation_timeout,
            env=env,
            check=False,
        )
        evaluation = json.loads(candidate_evidence.read_text(encoding='utf-8'))
        return {
            'decision': evaluation['decision'],
            'candidate_commit': candidate_commit,
            'candidate': candidate,
            'evaluator_exit_code': completed.returncode,
            'evaluator_output': completed.stdout[-16000:],
        }
    except subprocess.TimeoutExpired:
        return {'decision': 'FAIL', 'stage': 'candidate-execution', 'error': 'Protected evaluation timed out.', 'candidate': candidate}
    except subprocess.CalledProcessError as exc:
        return {'decision': 'FAIL', 'stage': 'candidate-execution', 'error': str(exc), 'candidate': candidate}
    finally:
        subprocess.run(
            ['git', 'worktree', 'remove', '--force', str(worktree_root)],
            cwd=root,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        shutil.rmtree(worktree, ignore_errors=True)



def write_manifest(evidence_dir: Path) -> None:
    files = {}
    for path in sorted(evidence_dir.iterdir()):
        if path.is_file() and path.name != "manifest.json":
            files[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
    (evidence_dir / "manifest.json").write_text(
        json.dumps(
            {"schema_version": 1, "evidence_sha256": files},
            indent=2,
            sort_keys=True,
        ) + "\n",
        encoding="utf-8",
    )


def cycle(root: Path, evidence_dir: Path) -> int:
    evidence_dir.mkdir(parents=True, exist_ok=True)
    if any(evidence_dir.iterdir()):
        raise RuntimeError("RSI evidence directory must be empty at cycle start.")
    if git(root, 'status', '--porcelain'):
        raise RuntimeError("RSI requires a clean working tree before a cycle starts.")
    baseline = git(root, 'rev-parse', 'HEAD')
    policy = load_policy(root)
    budget = policy['budget']

    max_calls = int(budget['max_proposer_calls_per_cycle'])
    max_candidates = int(budget['max_candidate_attempts_per_cycle'])
    max_context_chars = int(budget['max_context_chars'])
    max_output_tokens = int(budget['max_output_tokens'])
    max_total_tokens = int(budget['max_total_tokens_per_cycle'])
    require_usage = bool(budget.get('require_usage_telemetry', True))
    evaluation_timeout = int(policy['evaluation']['timeout_seconds'])

    started = time.monotonic()
    evidence: dict[str, Any] = {
        'schema_version': 3,
        'baseline_commit': baseline,
        'started_at': time.time(),
        'budget': {
            'max_proposer_calls_per_cycle': max_calls,
            'max_candidate_attempts_per_cycle': max_candidates,
            'max_context_chars': max_context_chars,
            'max_output_tokens': max_output_tokens,
            'max_total_tokens_per_cycle': max_total_tokens,
            'require_usage_telemetry': require_usage,
        },
    }

    proposer_calls = 0
    candidate_attempts = 0

    try:
        if not implementation_ready(policy):
            evidence['result'] = {
                'decision': 'BLOCKED',
                'stage': 'implementation-readiness',
                'error': (
                    'RSI implementation is not declared READY in the protected policy. '
                    'The proposer must not be called before mandatory implementation '
                    'components are implemented and independently verified.'
                ),
            }
            evidence['budget']['proposer_calls_used'] = proposer_calls
            evidence['budget']['candidate_attempts_used'] = candidate_attempts
            evidence['duration_seconds'] = round(time.monotonic() - started, 3)
            evidence['decision'] = evidence['result']['decision']
            (evidence_dir / 'cycle.json').write_text(
                json.dumps(evidence, indent=2, sort_keys=True) + '\n',
                encoding='utf-8',
            )
            write_manifest(evidence_dir)
            print(json.dumps(evidence, indent=2, sort_keys=True))
            return 1

        if max_calls < 1 or max_candidates < 1:
            raise RuntimeError('RSI budget policy disables candidate generation.')

        proposer_calls += 1
        if proposer_calls > max_calls:
            raise RuntimeError('RSI proposer call budget exceeded before proposal.')

        prompt, context_chars = proposer_prompt(root, baseline, max_context_chars, policy)
        evidence['prompt_context_chars'] = context_chars

        provider_secret_env = policy["provider"]["api_key_env"]
        provider_secret = os.environ.get(provider_secret_env, "")
        try:
            candidate, usage, model = call_proposer(prompt, max_output_tokens, policy)
        finally:
            # Do not leave the provider credential in this process while
            # candidate-controlled evaluation is running.
            os.environ.pop(provider_secret_env, None)
        evidence["proposer_model"] = model
        evidence["proposer_usage"] = usage
        evidence["proposer_usage_verified"] = (
            usage is not None and usage.get("total_tokens") is not None
        )
        candidate_text = json.dumps(candidate, sort_keys=True)
        leaks = [pattern.pattern for pattern in SECRET_PATTERNS if pattern.search(candidate_text)]
        if provider_secret and provider_secret in candidate_text:
            leaks.append('provider secret value appeared in proposer output')

        if leaks:
            evidence['result'] = {
                'decision': 'FAIL',
                'stage': 'candidate-validation',
                'secret_findings': sorted(set(leaks)),
            }
        elif require_usage and (usage is None or usage.get('total_tokens') is None):
            evidence['result'] = {
                'decision': 'BLOCKED',
                'stage': 'budget-verification',
                'error': 'Provider did not return OpenAI-compatible total token usage telemetry.',
            }
        elif usage is not None and usage['total_tokens'] > max_total_tokens:
            evidence['result'] = {
                'decision': 'BLOCKED',
                'stage': 'budget-verification',
                'error': (
                    f"Provider reported {usage['total_tokens']} total tokens, "
                    f"above the protected cycle budget of {max_total_tokens}."
                ),
            }
        else:
            candidate_attempts += 1
            if candidate_attempts > max_candidates:
                raise RuntimeError('RSI candidate-attempt budget exceeded before evaluation.')
            if 'baseline_commit' not in candidate:
                candidate['baseline_commit'] = baseline
            evidence['candidate'] = candidate
            evidence['result'] = apply_and_evaluate(
                root,
                baseline,
                candidate,
                evidence_dir,
                evaluation_timeout,
                policy,
            )
    except Exception as exc:
        evidence['result'] = {'decision': 'BLOCKED', 'stage': 'proposal', 'error': str(exc)}

    evidence['budget']['proposer_calls_used'] = proposer_calls
    evidence['budget']['candidate_attempts_used'] = candidate_attempts
    evidence['duration_seconds'] = round(time.monotonic() - started, 3)
    evidence['decision'] = evidence['result']['decision']
    (evidence_dir / 'cycle.json').write_text(
        json.dumps(evidence, indent=2, sort_keys=True) + '\n',
        encoding='utf-8',
    )
    write_manifest(evidence_dir)
    print(json.dumps(evidence, indent=2, sort_keys=True))
    return 0 if evidence['decision'] == 'PASS' else 1



def main() -> int:
    parser = argparse.ArgumentParser(description='Run one NOVA autonomous RSI cycle.')
    parser.add_argument('command', choices=['cycle'])
    parser.add_argument('--repo', default='.')
    parser.add_argument('--evidence-dir', default='.rsi-evidence')
    args = parser.parse_args()
    return cycle(Path(args.repo).resolve(), Path(args.evidence_dir).resolve())


if __name__ == '__main__':
    raise SystemExit(main())
